spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/echo_film?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8090
  servlet:
    context-path: /api


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true


mybatis-plus:
  global-config:
    db-config:
      table-prefix:
      id-type: auto
  type-aliases-package: com.yiyu.echofilmspringboot
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
